name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo add-apt-repository 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial main'
          sudo add-apt-repository 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe'
          sudo apt update
          sudo apt install libgl1-mesa-dev qttools5-dev g++-5 gcc-5

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
           -DCMAKE_C_COMPILER='/usr/bin/gcc-5 -static' \
           -DCMAKE_CXX_COMPILER='/usr/bin/g++-5 -static' \
           -DCMAKE_BUILD_TYPE=Release \
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json \
           -DCMAKE_INSTALL_PREFIX:PATH=/home/runner/UltimMC/UltimMC \
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ \
           -DLauncher_PASTE_EE_API_KEY:STRING=utLvciUouSURFzfjPxLBf5W4ISsUX4pwBDF7N1AfZ \
           -DLauncher_ANALYTICS_ID:STRING=UA-87731965-2 \
           -DLauncher_LAYOUT=lin-nodeps \
           -DLauncher_BUILD_PLATFORM=lin64 \
           $GITHUB_WORKSPACE

      - name: Compile
        run: |
          cd build
          make tcversion
          make -j$(nproc)

      - name: Install
        run: |
          cd build
          make install
          chmod +x /home/runner/UltimMC/UltimMC/UltimMC
          chmod +x /home/runner/UltimMC/UltimMC/bin/UltimMC

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: mmc-cracked-lin64
          path: /home/runner/UltimMC


